kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: event-logger-operator
subjects:
  - kind: ServiceAccount
    name: event-logger-operator
    namespace: { { .Release.Namespace } }
roleRef:
  kind: ClusterRole
  name: event-logger-operator
  apiGroup: rbac.authorization.k8s.io
