apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: event-logger-operator
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - secrets
      - serviceaccounts
    verbs:
      - "*"
  - apiGroups:
      - ""
    resources:
      - events
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
      - rolebindings
    verbs:
      - "*"
  - apiGroups:
      - eventlogger.bakito.ch
    resources:
      - "*"
    verbs:
      - "*"

---
# extend edit and view cluster roles
# see documentation: https://kubernetes.io/docs/reference/access-authn-authz/rbac/#user-facing-roles

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlogger-bakito-ch-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups:
      - eventlogger.bakito.ch
    resources:
      - eventloggers
    verbs:
      - create
      - delete
      - get
      - list
      - patch
      - update

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: eventlogger-bakito-ch-view
  labels:
    rbac.authorization.k8s.io/aggregate-to-view: "true"
rules:
  - apiGroups:
      - eventlogger.bakito.ch
    resources:
      - eventloggers
    verbs:
      - get
      - list
