apiVersion: apps/v1
kind: Deployment
metadata:
  name: event-logger-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      name: event-logger-operator
  template:
    metadata:
      labels:
        name: event-logger-operator
    spec:
      serviceAccountName: event-logger-operator
      containers:
        - name: event-logger-operator
          image: "quay.io/bakito/k8s-event-logger-operator:v0.1.3"
          imagePullPolicy: Always
          command:
            - /opt/go/k8s-event-logger-operator
          args:
            - "--zap-level=info"
            - "--zap-time-encoding=iso8601"
          env:
            - name: OPERATOR_NAME
              value: event-logger-operator
            - name: WATCH_NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: EVENT_LOGGER_IMAGE
              value: "quay.io/bakito/k8s-event-logger:v0.1.3"
            - name: LOGGER_POD_REQUEST_CPU
              value: "100m"
            - name: LOGGER_POD_REQUEST_MEM
              value: "64Mi"
            - name: LOGGER_POD_LIMIT_CPU
              value: "200m"
            - name: LOGGER_POD_LIMIT_MEM
              value: "256Mi"
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 200m
              memory: 512Mi
