apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: event-logger-operator
rules:
  - apiGroups:
      - ""
    resources:
      - configmaps
      - services
      - services/finalizers
    verbs:
      - "*"
  - apiGroups:
      - apps
    resources:
      - deployments
      - replicasets
    verbs:
      - "*"
  - apiGroups:
      - apps
    resourceNames:
      - event-logger-operator
    resources:
      - deployments/finalizers
    verbs:
      - update
  - apiGroups:
      - rbac.authorization.k8s.io
    resources:
      - roles
    verbs:
      - list
  - apiGroups:
      - monitoring.coreos.com
    resources:
      - servicemonitors
    verbs:
      - get
      - create
  - apiGroups:
      - eventlogger.bakito.ch
    resources:
      - "*"
    verbs:
      - "*"
