apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: |-
      [
        {
          "apiVersion": "eventlogger.bakito.ch/v1",
          "kind": "EventLogger",
          "metadata": {
            "name": "example-eventlogger"
          },
          "spec": {
            "eventTypes": [
              "Warning"
            ],
            "kinds": [
              {
                "name": "ConfigMap"
              },
              {
                "name": "Pod"
              }
            ]
          }
        }
      ]
    capabilities: Basic Install
  name: k8s-event-logger-operator.v0.1.3
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: EventLogger is the Schema for the eventloggers API
      kind: EventLogger
      name: eventloggers.eventlogger.bakito.ch
      version: v1
  description: Placeholder description
  displayName: K8s Event Logger Operator
  install:
    spec:
      deployments:
      - name: event-logger-operator
        spec:
          replicas: 1
          selector:
            matchLabels:
              name: event-logger-operator
          strategy: {}
          template:
            metadata:
              labels:
                name: event-logger-operator
            spec:
              containers:
              - args:
                - --zap-level=info
                - --zap-time-encoding=iso8601
                command:
                - /opt/go/k8s-event-logger-operator
                env:
                - name: OPERATOR_NAME
                  value: event-logger-operator
                - name: WATCH_NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.annotations['olm.targetNamespaces']
                - name: POD_NAME
                  valueFrom:
                    fieldRef:
                      apiVersion: v1
                      fieldPath: metadata.name
                - name: EVENT_LOGGER_IMAGE
                  value: quay.io/bakito/k8s-event-logger:v0.1.3
                - name: LOGGER_POD_REQUEST_CPU
                  value: 100m
                - name: LOGGER_POD_REQUEST_MEM
                  value: 64Mi
                - name: LOGGER_POD_LIMIT_CPU
                  value: 200m
                - name: LOGGER_POD_LIMIT_MEM
                  value: 256Mi
                image: quay.io/bakito/k8s-event-logger-operator:v0.1.3
                imagePullPolicy: Always
                name: event-logger-operator
                resources:
                  limits:
                    cpu: 200m
                    memory: 512Mi
                  requests:
                    cpu: 100m
                    memory: 128Mi
              serviceAccountName: event-logger-operator
      permissions:
      - rules:
        - apiGroups:
          - ""
          resources:
          - configmaps
          - services
          - services/finalizers
          verbs:
          - '*'
        - apiGroups:
          - apps
          resources:
          - deployments
          - replicasets
          verbs:
          - '*'
        - apiGroups:
          - apps
          resourceNames:
          - event-logger-operator
          resources:
          - deployments/finalizers
          verbs:
          - update
        - apiGroups:
          - rbac.authorization.k8s.io
          resources:
          - roles
          verbs:
          - list
        - apiGroups:
          - monitoring.coreos.com
          resources:
          - servicemonitors
          verbs:
          - get
          - create
        - apiGroups:
          - eventlogger.bakito.ch
          resources:
          - '*'
          verbs:
          - '*'
        serviceAccountName: event-logger-operator
    strategy: deployment
  installModes:
  - supported: true
    type: OwnNamespace
  - supported: true
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  maturity: alpha
  provider: {}
  replaces: k8s-event-logger-operator.v0.0.0
  version: 0.1.3
